# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/fft',
                'doc_host': 'https://LucidCatnap.github.io',
                'git_url': 'https://github.com/LucidCatnap/fft',
                'lib_path': 'fft'},
  'syms': {'fft.core': {'fft.core.foo': ('core.html#foo', 'fft/core.py')}}}
